name: Bug Report
description: Report a bug or issue with SuperMini
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the information below to help us diagnose and fix the issue.

  - type: input
    id: version
    attributes:
      label: SuperMini Version
      description: What version of SuperMini are you running?
      placeholder: e.g., v2.0.0, latest from main branch
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Windows 10
        - Windows 11
        - Other
    validations:
      required: true

  - type: input
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: e.g., 3.9.7, 3.10.0
    validations:
      required: true

  - type: dropdown
    id: ai-model
    attributes:
      label: AI Model Being Used
      description: Which AI model were you using when the bug occurred?
      options:
        - Claude API
        - Ollama (qwen2.5-coder:7b)
        - Ollama (llama3.2:3b)
        - Ollama (other model)
        - Not applicable
        - Unknown
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Enter '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Messages / Logs
      description: If applicable, add any error messages or log output
      placeholder: |
        Paste error messages here...
        Check ~/SuperMini_Output/logs/supermini.log for detailed logs
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop images here or paste image URLs

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm the following before submitting
      options:
        - label: I have searched existing issues to ensure this hasn't been reported before
          required: true
        - label: I have checked the troubleshooting section in the README
          required: true
        - label: I have included all relevant information requested above
          required: true
        - label: I am willing to help test a fix for this issue
          required: false